### ISSUE TITLE
In NearBy  inspite of the alert popup"No Result Found". Still able to search the nearby data

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#10]
Refer the Screenshot.
![ss70_citizen_13sep16](https://cloud.githubusercontent.com/assets/22045189/18470097/a9f230c2-79c8-11e6-9284-b58a79db4388.jpg)

**Comment by mariya-esri** [comment]
![reply](https://cloud.githubusercontent.com/assets/22171626/18500975/84beb9fe-7a6a-11e6-9ab7-fbed3e1e608a.png)

**Comment by mariya-esri** [comment]
This issue was fixed mam, I attached the screenshots for your reference.

**Comment by ArchanaSingh2305** [comment]
@mariya-esri Please do not close any issue. The issues can be closed only by the Tester. If you have any clarification to make please comment on the issue and request tester to close it.

**Comment by ArchanaSingh2305** [comment]
@AchanaJoshi please retest and call @mariya-esri to close the issue.

**Comment by mariya-esri** [comment]
Ok mam, Sorry

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305 @mariya-esri 
Steps to recreate
1. Login to the application & search any place
2.Click on facility  & click on show list
3. Zoom to the level where facilities are not available. message will pop up
4. Click on Zoom out button 
Result: Search Facilities still works and result in show list gets updated with message " No result found"

**Comment by mariya-esri** [comment]
Issues Fixed and updated in SVN.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305 @mariya-esri :Verified and Closed
