### ISSUE TITLE
If the same names are available in Search POI Tool. Favourite is not working as expected

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#11]
Refrer#
![ss72_citizen_13sep16](https://cloud.githubusercontent.com/assets/22045189/18471019/3af4d684-79cd-11e6-8dee-9b7716fcacae.jpg)

Steps:
1. Search Amba Village. (We have 10 records with same name)
2. Select any one  from the list and click on Favorite
3.  Again Click on some other Amba Village from the drop down. Favorite is already selected the newly selected data.

**Comment by sksaurav03** [comment]
@AchanaJoshi  Kindly witness the changes after the site gets Re-Hosted.

**Comment by sksaurav03** [comment]
@AchanaJoshi Kindly witness the changes after the site gets Re-Hosted.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305 @sksaurav03 

Same Issue need to be fixed Like / Dislike button--> Amba Village
Ex.
1. Amba Village (72.723342 / 24.442134)--> Like (0) Dislike (1)
2. Amba Village (73.257302/ 24.063933)--> Like (0) Dislike (1)
Change --> Like (1) and Dislike (0)
3. Amba Village (72.723342 / 24.442134)--> Like (1) Dislike (0)

**Comment by ArchanaSingh2305** [comment]
@sksaurav03 Please check this issue and fix.

**Comment by ArchanaSingh2305** [comment]
Issue has been fixed and rehosted.
@AchanaJoshi Please test it.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305 @sksaurav03 

For same location name (Check Amba Village,  Begun, Chittaurgarh), we have 2 records. Previously selected favorite is not retaining the value.

**Comment by sksaurav03** [comment]
@AchanaJoshi @ArchanaSingh2305 
The favourite issue has been fixed and site is Hosted. Kindly witness the changes

**Comment by AchanaJoshi** [comment]
@sksaurav03 Verified and Closed
