### ISSUE TITLE
Login to the citizen application with Firefox. "Null" error popsup

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#12]
Refer#
![firefox](https://cloud.githubusercontent.com/assets/22045189/18541323/18703a6a-7b42-11e6-80f1-3ceb9dab8185.jpg)

**Comment by ArchanaSingh2305** [comment]
The bug has been fixed and the code is committed in SVN. Will be available for testing after rehosting.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305  Verified and Closed
