### ISSUE TITLE
Names are going beyond map

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#14]
![citizen_basemap](https://cloud.githubusercontent.com/assets/22045189/18660987/291ca90a-7f31-11e6-9485-34df11985d3f.jpg)
Added  on the tracker on 19Aug16

**Comment by ArchanaSingh2305** [comment]
As per Shantonu, this issue will be taken up in the next phase when more changes would be done in the basemap and the caching would be done for the basemap again after that from scratch(caching the map service is a long and time consuming process).

@AchanaJoshi Please close this issue for now.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305 Based on developer comment. Closing the issue
