### ISSUE TITLE
Without adding maximum number of stops alert pops up. 

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#15]
@ritanshu-goel 
1. Not able to add more that 9 stops before that message comes"Maximum number of stops has been reached". Though I can add 10 stops
2. Once I am able to add 11 stops. But the limit of adding stops is 10
Refer#
![ss74_health_21sep16](https://cloud.githubusercontent.com/assets/22045189/18709026/8ae0ba88-801b-11e6-99cb-c432a35dac25.jpg)

**Comment by AchanaJoshi** [comment]
@ritanshu-goel  Able to add more than 10 points. Refer#
![ss74_citizen_22sep16](https://cloud.githubusercontent.com/assets/22045189/18740070/587e5bc2-80c5-11e6-8f9f-eb67a865ca00.jpg)

**Comment by ArchanaSingh2305** [comment]
@AchanaJoshi Whats the status of this issue? Is this still open?

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305  Yesterday, I checked with Ritanshu he has not started working on it. No update on Github either.
