### ISSUE TITLE
Search POI showing outside Rajasthan

### ISSUE THREAD

**Issue by shomevarma** [DoITRaj/DoIT-Citizen#16]
Type : Hotel
Select Rawat Hotel
Searched Hotel is displayin
![searched poi is outside rajasthan](https://cloud.githubusercontent.com/assets/22213405/18910196/87111d34-8594-11e6-8456-da71ca1d6f88.jpg)
![Uploading Rawat Hotel.jpg…]()

g Outside Rajasthan

**Comment by ArchanaSingh2305** [comment]
Fixed and hosted.
@ShomeTester Please test it and close.

**Comment by ShomeTester** [comment]
Closed
