### ISSUE TITLE
Auto Suggestion Repeats

### ISSUE THREAD

**Issue by shomevarma** [DoITRaj/DoIT-Citizen#17]
Shergarh Fort

Albert hall : As depicted in screenshot for option 3 data not loaded correctly.

Two values in Auto suggestion both pointing to same location
![auto suggestion -repeat-same location](https://cloud.githubusercontent.com/assets/22213405/18910240/bd4b38a8-8594-11e6-9419-5f89d8fa3e95.jpg)
![auto suggestion -repeat](https://cloud.githubusercontent.com/assets/22213405/18910242/bd536d02-8594-11e6-845e-7746faea3adf.jpg)

**Comment by ArchanaSingh2305** [comment]
@ShomeTester This is the same issue as #20 . Duplicate issues. Please either of the two.

**Comment by ShomeTester** [comment]
Sure. Agreed. Closed
