### ISSUE TITLE
Map not loading correctly

### ISSUE THREAD

**Issue by shomevarma** [DoITRaj/DoIT-Citizen#18]
Type Atru and select Atru Railway Station
![atru railway station-map not loading correctly](https://cloud.githubusercontent.com/assets/22213405/18910290/f3f52c24-8594-11e6-93d8-498be2a43e57.jpg)

**Comment by ArchanaSingh2305** [comment]
@shomevarma There might be some network issue at that time. Could you please check again?

Its working at my end.
![image](https://cloud.githubusercontent.com/assets/6047099/18910590/51746f12-8596-11e6-9a50-37a3a86073e4.png)

**Comment by ArchanaSingh2305** [comment]
@ShomeTester The bug has been fixed and hosted. Please test and close.

**Comment by ShomeTester** [comment]
Closed.
