### ISSUE TITLE
On Reset, Searched assets are not clearing from map.

### ISSUE THREAD

**Issue by ShomeTester** [DoITRaj/DoIT-Citizen#19]
Searched Assets and then Reset. Observed when browser history is not cleared.
![previous results not clearing](https://cloud.githubusercontent.com/assets/22493300/18942121/2ecc3974-8634-11e6-89f7-eb9cf092be4e.jpg)

**Comment by AchanaJoshi** [comment]
@mariya-esri 
Steps to recreate
1. Search NearBy Facility
2. Click on the facility on map. Facility should get highlighted 
3. Click on "Show Full Screen " button such that identify tool is invoked

Check the result: Icon will remain on the map

**Comment by ArchanaSingh2305** [comment]
Issue resolved. Application has been rehosted. Please test and close the bug.

**Comment by AchanaJoshi** [comment]
@mariya-esri  Verified and Closed
