### ISSUE TITLE
Direction Textbox to provide suggestion from Rajasthan only while option to select pan india. currently it shows pan india

### ISSUE THREAD

**Issue by ArchanaSingh2305** [DoITRaj/DoIT-Citizen#2]
Direction Textbox to provide suggestion from Rajasthan only while option to select pan india. currently it shows pan india

**Comment by ArchanaSingh2305** [comment]
@ritanshu-goel please update the status to Fixed once done. and remove the label "In Progress"

**Comment by ritanshu-goel** [comment]
This is done. Few UI related issues are there. which I will resolve tomorrow.

**Comment by ritanshu-goel** [comment]
It will reflect after rehosting.

**Comment by ArchanaSingh2305** [comment]
@AchanaJoshi Application has been rehosted. Please test.

**Comment by AchanaJoshi** [comment]
@ritanshu-goel: Verified and Closed
Tested Url: http://gistest1.rajasthan.gov.in/citizen/#
