### ISSUE TITLE
On searching, multiple suggestion displays for single record. Many Points to same location

### ISSUE THREAD

**Issue by ShomeTester** [DoITRaj/DoIT-Citizen#20]
Enter Temple, Multiple Shiv Mandir displays as auto suggestion. 
Enter Albert Museum, Multiple auto suggestions displays with the same name. 
![auto suggestion -repeat-same location](https://cloud.githubusercontent.com/assets/22493300/18942201/c885e628-8634-11e6-95de-4af8f4f02e50.jpg)
![auto suggestion -repeat](https://cloud.githubusercontent.com/assets/22493300/18942203/d075739e-8634-11e6-8197-b20fbaadc25c.jpg)

**Comment by ArchanaSingh2305** [comment]
@ShomeTester @AchanaJoshi The data provided by HERE contains duplicate records which cannot be removed right now. This issue has been conveyed to HERE Team and they need to take to clean up the duplicate records. We would have to wait until then. Therefore we wont be fixing this for now.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305 @ShomeTester 
Discussed with Shome. He is agreed to close it based on developer comments
