### ISSUE TITLE
Enter 'Gramin Bank', all Gramin banks not displaying as auto suggestion.

### ISSUE THREAD

**Issue by ShomeTester** [DoITRaj/DoIT-Citizen#21]
On Passing , Gramin Bank, All Gramin Banks, e.g Jaipur Thar Gramin Bank not coming

**Comment by ArchanaSingh2305** [comment]
Only top 20 search results are shown in the suggestion. Fore refined results users can use the extent based option to view all the Gramin banks in the extent of the map. 

I am marking this as Invalid.

**Comment by ArchanaSingh2305** [comment]
@ShomeTester Please close this issue.

**Comment by ShomeTester** [comment]
Yes. Initially 'Extent Based Search' was not on. Now when 'Extent Based Search' is on , then on entering 'Gramin' as value in 'Search POI' 'Jaipur Thar Gramin Bank' is coming as auto suggestion.
