### ISSUE TITLE
Not All records are displaying

### ISSUE THREAD

**Issue by ShomeTester** [DoITRaj/DoIT-Citizen#22]
On Searching NH 3 , neither auto suggestion displays nor correct message displays.

**Comment by ArchanaSingh2305** [comment]
This is because there are no data pertaining to NH3 in the service.

**Comment by ArchanaSingh2305** [comment]
@ShomeTester Please close this issue.

**Comment by ShomeTester** [comment]
Closed as searched data as it falling near NH 3 but the address does not contain NH 3. Therefore closed.
