### ISSUE TITLE
On searching assets, progress bar continue to display.

### ISSUE THREAD

**Issue by ShomeTester** [DoITRaj/DoIT-Citizen#23]
![progress bar continue to display](https://cloud.githubusercontent.com/assets/22493300/18942381/361ebd12-8636-11e6-8428-9191e6ebc50a.jpg)

**Comment by mariya-esri** [comment]
Fixed

**Comment by mariya-esri** [comment]
It is working fine now, yesterday it may happened due to network issue.

**Comment by ShomeTester** [comment]
Till Now, not reproducible. If found again will inform you. Closed.
