### ISSUE TITLE
On entering full text , displaying auto suggestions are not correct.

### ISSUE THREAD

**Issue by ShomeTester** [DoITRaj/DoIT-Citizen#24]
Enter Industrial and check the auto suggestions.
![industrial](https://cloud.githubusercontent.com/assets/22493300/18952591/ec42a85c-8667-11e6-8404-dbb983feeba1.jpg)

**Comment by ArchanaSingh2305** [comment]
@ShomeTester This as per functionality.

"Industrial" is actually a sub category and that why you can see all the POIs with industrial icon.

**Comment by ShomeTester** [comment]
As discussed the complete list of Sub Categories have been shared by the developer.
