### ISSUE TITLE
Not able to Search locations available in Direction Search using Search POI. Example :Sethi Colony Path

### ISSUE THREAD

**Issue by ShomeTester** [DoITRaj/DoIT-Citizen#26]
• Search Jaipur City—Search POI—Map extent is set
• Search Shree Sriniwa S Chamadiya Library----Search POI
• Search Bus Stand –Search Nearby of Sriniwa S Chamadiya Library
• Use direction tool
• First point the bus stand and second Point is library
• Directions displays on map. The last point is Sethi Colony Path.

Now try searching Sethi Colony Path using Search Nearby.

The auto suggestion displays Sethi Colony Park and not Sethi Colony Path.

**Comment by ArchanaSingh2305** [comment]
Sethi Colony is coming from the NamedPlc Table (Point data) and the Sethi Colony Park is available in the LandUseA table (Polygon data). Both the sources are different. Thats why not able to saerch in SearchPOI.

**Comment by ShomeTester** [comment]
Closed as per discussion with developer. Stated as client requiremnt.
