### ISSUE TITLE
At 0.2 KM, duplicate labels are displayed. Example : Shaheed Smarak Park.

### ISSUE THREAD

**Issue by ShomeTester** [DoITRaj/DoIT-Citizen#27]
![shaheed smarak park](https://cloud.githubusercontent.com/assets/22493300/19033674/4327a39e-897d-11e6-87a6-59c279e8f74c.jpg)

**Comment by ArchanaSingh2305** [comment]
“Shaheed Smarak Park” is actually 2 different features(polygons) separated by a road, hence the labels are showing up two times.

**Comment by ArchanaSingh2305** [comment]
The caching is going on for basemaps and once completed the lower levels of details would be available.

**Comment by ShomeTester** [comment]
Closed as per developer comments
