### ISSUE TITLE
Not able to identify Shaheed Smark Park using  Search Nearby.

### ISSUE THREAD

**Issue by ShomeTester** [DoITRaj/DoIT-Citizen#28]
![search park---saheed smark not found](https://cloud.githubusercontent.com/assets/22493300/19033726/86543d80-897d-11e6-979f-c422b5cdf764.jpg)

Set Jaipur city as POI. Extent based search

**Comment by ArchanaSingh2305** [comment]
@ShomeTester clarification has been provided in above comments. Please close the bug as it has been marked invalid.

**Comment by ArchanaSingh2305** [comment]
As discussed with Sanjeevi, we are not to change or alter the subcategory field provided by Here Maps as they might be subjected to change at a later stage. We will stick with the data shared by them as of now, in case if there is any change from Here the data will be changed and it should reflect the same in the application.

**Comment by ShomeTester** [comment]
Closed as per developer remark
