### ISSUE TITLE
Lable is not getting clear on map

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#29]
![ss89_citizen_5oct16](https://cloud.githubusercontent.com/assets/22045189/19110859/0a4d65ce-8b1a-11e6-97eb-54df6cb5009b.jpg)

**Comment by ArchanaSingh2305** [comment]
Application has been rehosted. Please test and close the bug.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305 Verified and Closed
