### ISSUE TITLE
same Category should have the same icon in Search NearBy and POI

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#30]
@ArchanaSingh2305 

Please keep the same icon for the following category
1. Restaurant
2. Shopping
3. Railway Station

**Comment by ArchanaSingh2305** [comment]
@AchanaJoshi Fixed and hosted. Please test and close.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305  Verified and Closed
