### ISSUE TITLE
Background image is not coming. Refer# Background

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#35]
@ArchanaSingh2305 
![background](https://cloud.githubusercontent.com/assets/22045189/20472977/a24b5dc0-afe3-11e6-9b06-8b043b8f3fd7.jpg)

**Comment by ArchanaSingh2305** [comment]
Fixed

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305  Verified & Closed
