### ISSUE TITLE
SSO login is coming on top of “Zoom In/ Zoom Out” button

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#36]
![sso login](https://cloud.githubusercontent.com/assets/22045189/20473068/19b4bf28-afe4-11e6-8703-c6c644c94f16.jpg)

**Comment by ArchanaSingh2305** [comment]
Fixed

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305  Verified & Closed

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305  Verified & Closed
