### ISSUE TITLE
Click on reverse direction "Direction from here" and "Direction to here" options gets disable 

### ISSUE THREAD

**Issue by ArchanaSingh2305** [DoITRaj/DoIT-Citizen#4]
Step1: Click on Direction from here
Step2: Click on Reverse Direction (More than one time0
Result: Both the option get disable

Its not working vice versa
![ss48_citizen_16aug16](https://cloud.githubusercontent.com/assets/6047099/18311828/28375100-7524-11e6-87af-5b66408d1adc.jpg)

**Comment by ArchanaSingh2305** [comment]
@ritanshu-goel please update the label to _fixed_ after fixing
@AchanaJoshi Please test it once fixed.

**Comment by ritanshu-goel** [comment]
This is done and tested by Tester also.

**Comment by ArchanaSingh2305** [comment]
@ritanshu-goel once you are done fixing, add the label **Fixed** and remove the label **In Progress**.
Please do not close it. Let @AchanaJoshi **Close** it

**Comment by ArchanaSingh2305** [comment]
@AchanaJoshi Please test and close.

**Comment by AchanaJoshi** [comment]
@ritanshu-goel: Above mentioned issue is Verified and Closed
Tested Url: http://gistest1.rajasthan.gov.in/citizen
