### ISSUE TITLE
Login to the application on production got error message for “Post Create”

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#40]
![postcreate](https://cloud.githubusercontent.com/assets/22045189/20473276/87bf9dc0-afe5-11e6-8a73-719adaf753f9.jpg)

**Comment by ArchanaSingh2305** [comment]
Fixed

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305  Verified & Closed
