### ISSUE TITLE
Direction-> Not able to print the map at Mobile / production. Got error alert on mobile.  It’s coming for staging

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#41]
![citizen_print](https://cloud.githubusercontent.com/assets/22045189/20473333/e8791970-afe5-11e6-8155-0afce0aaf389.jpg)

**Comment by ArchanaSingh2305** [comment]
Fixed.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305  Verified & Closed
