### ISSUE TITLE
Callout is coming on left panel. 

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#43]
![callout on left panel](https://cloud.githubusercontent.com/assets/22045189/20473421/993f9586-afe6-11e6-9ca5-271592e583a2.jpg)

**Comment by ArchanaSingh2305** [comment]
Fixed.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305  Verified & Closed
