### ISSUE TITLE
Text for the searched facility can be warped, if it exceeds the length

### ISSUE THREAD

**Issue by AchanaJoshi** [DoITRaj/DoIT-Citizen#46]
![facilitytext](https://cloud.githubusercontent.com/assets/22045189/20473537/5fe9bebe-afe7-11e6-9a18-9d31be38ad5b.jpg)

**Comment by ArchanaSingh2305** [comment]
Fixed.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305  Verified & Closed
