### ISSUE TITLE
Scrollbar panel is hiding

### ISSUE THREAD

**Issue by ArchanaSingh2305** [DoITRaj/DoIT-Citizen#5]
![ss62_citizen_18aug16](https://cloud.githubusercontent.com/assets/6047099/18311910/a54dd5a6-7524-11e6-8334-c9a9a61d15bc.jpg)

**Comment by ritanshu-goel** [comment]
Fixed and tested by tester too.

**Comment by ArchanaSingh2305** [comment]
@ritanshu-goel Please dont forget to remove **In Progress** label once fixed

**Comment by AchanaJoshi** [comment]
This bug is fixed and Closed
