### ISSUE TITLE
Switch the selected facility on the map. Focus is  shifting on map but  focus is not shifting on show lis but vise versa is working fine

### ISSUE THREAD

**Issue by ArchanaSingh2305** [DoITRaj/DoIT-Citizen#6]
Switch the selected facility on the map. Focus is  shifting on map but  focus is not shifting on show lis but vise versa is working fine

**Comment by ArchanaSingh2305** [comment]
@AchanaJoshi the bug has been fixed and rehosted. Please test.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305 & @ritanshu-goel : Reopen. Checked for 5 min Only progress bar was moving but the application was not loaded with the change in focus.
Refer#
![ss68_citizen_13sep16](https://cloud.githubusercontent.com/assets/22045189/18466423/49317bf8-79b9-11e6-97c3-106620f8f3ff.jpg)

**Comment by ArchanaSingh2305** [comment]
@mariya-esri please check this issue. Its not fixed.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305 @mariya-esri 

Mariya has checked the issue on my system via Team Viewer.Please Fix  it

**Comment by mariya-esri** [comment]
Issue fixed and updated in SVN

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305 @mariya-esri : 

Verified and Closed
