### ISSUE TITLE
Search Nearby tool and then Click on direction tool . Not able to select Point 1 on map 

### ISSUE THREAD

**Issue by ArchanaSingh2305** [DoITRaj/DoIT-Citizen#7]
Search Nearby tool and then Click on direction tool . Not able to select Point 1 on map 
![ss70_citizen_31aug16](https://cloud.githubusercontent.com/assets/6047099/18312036/3c26e08a-7525-11e6-89fd-e64b484e5a42.jpg)

**Comment by ritanshu-goel** [comment]
Not reflect. Discussed with tester..

**Comment by AchanaJoshi** [comment]
@ritanshu-goel : Above mentioned issue is Verified and Closed
Tested Url: http://gistest1.rajasthan.gov.in/citizen/
