### ISSUE TITLE
Print should have all options

### ISSUE THREAD

**Issue by ArchanaSingh2305** [DoITRaj/DoIT-Citizen#8]
In print we should have options as
1. Text only
2. Map & Text
3. Map only

**Comment by ritanshu-goel** [comment]
@AchanaJoshi : hello ma'am, It is also fixed please test it after re-hosting.

**Comment by mariya-esri** [comment]
Please test it also. It is available in hosted version @AchanaJoshi

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305 In Chrrome "Select Print Layout' is not displaying completely
![print](https://cloud.githubusercontent.com/assets/22045189/18624197/43cce63a-7e63-11e6-9565-1d866f2264f3.png)

**Comment by ArchanaSingh2305** [comment]
@ritanshu-goel please check this issue and resolve.

**Comment by ritanshu-goel** [comment]
issue Resolved. Will reflect after rehosting..

**Comment by AchanaJoshi** [comment]
@ritanshu-goel : Verified and Closed
